;all constants
;for worldcreator
;constants for worldcreator handling (errors/warnings/catchups)

Enumeration
  #WC_ERROR_FILE_NOT_FOUND
  #WC_ERROR_NOT_DEFINED
  #WC_ERROR_CAN_NOT_CREATE_MENU
  #WC_ERROR_NEED_SOURCE
  #WC_ERROR_CAN_NOT_CREATE_OBJECT
  #WC_ERROR_CAN_NOT_ADD_OBJECT
  #WC_ERROR_NOT_SAVED_CONTENT_WILL_BE_LOST
  #WC_ERROR_DELPOINTER_MISSING
  #WC_ERROR_ASK_UPDATE_ASSET_DIRECTORY
EndEnumeration

;window handler

Enumeration
#WC_MENU_TITLE
#WC_MENU_LOAD_MAP
#WC_MENU_SAVE_MAP
#WC_MENU_QUIT
#WC_MENU_SET_RESURCE
#WC_MENU_SET_RESOURCE_SOUND
#WC_MENU_RESTART_SYSTEM
#WC_MENU_REDO
#WC_MENU_UNDO
#WC_MENU_NEW
#WC_LAYER_M1  ;M= MINUS (LAYER -1.....)
#WC_LAYER_M2
#WC_LAYER_M3
#WC_LAYER_M4
#WC_LAYER_M5
#WC_LAYER_M6
#WC_LAYER_M7
#WC_LAYER_M8
#WC_LAYER_M9
#WC_LAYER_M10
#WC_LAYER_M11
#WC_LAYER_M12
#WC_LAYER_M13
#WC_LAYER_M14
#WC_LAYER_M15
#WC_LAYER_0
#WC_LAYER_1
#WC_LAYER_2
#WC_LAYER_3
#WC_LAYER_4
#WC_LAYER_5
#WC_LAYER_6
#WC_LAYER_7
#WC_LAYER_8
#WC_LAYER_9
#WC_LAYER_10
#WC_SHOW_ACTUAL_LAYER
#WC_SHOW_ALL_LAYER
#WC_MENU_REMOVE_OBJECT
#WC_MENU_ADD_OBJECT
#WC_MENU_SHOW_LAYER_ID
#WC_MENU_DO_NOT_SHOW_LAYER_ID
#WC_MENU_SHOW_ENGINE_AREA
#WC_MENU_MOVE_MAP_OBJECT_SIZE
#WC_MENU_MOVE_BY_OBJECT_GRID
#WC_MENU_MOVE_MAP_PER_PIXEL
#WC_ADD_SOUND_TO_MAP
#WC_REMOVE_SOUND_FROM_MAP
#WC_SOUND_PLAY
#WC_SOUND_STOP
#WC_USE_RASTER_YES
#WC_USE_RASTER_NO
#WC_USE_AUTO_LAYER
#WC_DO_NOT_USE_AUTO_LAYER
#USE_CACHE
#WC_MENU_INFO
#WC_MENU_BLANK
#WC_PROGRESS_BAR_WINDOW
#WC_MENU_START_PROCEDURAL
#WC_AUTO_PLACE
#WC_DEFAULT
#WC_AREA_SAVE_AS
#WC_AREA_LOAD
#WC_AREA_ADD
#WC_SILENT
#WC_ROTATE
#WC_FLIP_MAP_H
#WC_FLIP_MAP_V
#WC_MENU_ADD_MAP_TEMPLATE
#WC_MENU_TEMPLATE_SHOW
#WC_HIDE_TEMPLATE
#WC_TEMPLATE_TRANSPARENCY_ADD
#WC_TEMPLATE_TRANSPARENCY_REMOVE
#WC_VIEW_800_450
#WC_VIEW_1000_564
#WC_VIEW_1280_720
#WC_VIEW_1440_1080
#WC_VIEW_1600_900
#WC_VIEW_1920_1080
#WC_SELECT_ARENA_GFX
#WC_MAP_INFO
#WC_MENU_MAP_PAUSE_NO
#WC_MENU_MAP_PAUSE_YES
#WC_MENU_MAP_USE_RESPAWN_NO
#WC_MENU_MAP_USE_RESPAWN_YES
#WC_MENU_MAP_USE_QUEST_SYSTEM_YES
#WC_MENU_MAP_USE_QUEST_SYSTEM_NO
#WC_MENU_MAP_NO_FIGHT
#WC_MENU_MAP_FIGHT
#WC_MENU_DAYTIMER_ON
#WC_MENU_DAYTIMER_OFF
#WC_MENU_MAP_IS_ARENA_YES
#WC_MENU_MAP_IS_ARENA_NO
#WC_MENU_MAP_NO_SCROLL
#WC_MENU_MAP_SCROLL
#WC_SHOW_VERSION_YES
#WC_SHOW_VERSION_NO
#WC_TIMER_SWITCH_MAP_0
#WC_TIMER_SWITCH_MAP_1000  ;map autoswitch system, if value >0 map will switch to next map in switchlist, after time (ms)
#WC_TIMER_SWITCH_MAP_2000
#WC_TIMER_SWITCH_MAP_3000
#WC_TIMER_SWITCH_MAP_5000
#WC_TIMER_SWITCH_MAP_10000
#WC_TIMER_SWITCH_MAP_ON_TRIGGER
#WC_SWITCH_MAP_TOUCH
#WC_SWITCH_MAP_TOUCH_DESELECT
#WC_MAP_SHOW_TIMER
#WC_MAP_SHOW_TIMER_NOT
#WC_MAP_USE_VIEW_STAMP
#WC_MAP_DO_NOT_USE_VIEW_STAMP
#WC_MAP_USE_FOG_OF_WAR
#WC_MAP_DO_NOT_USE_FOG_OF_WAR
#WC_MENU_NO_GLOBAL_EFFECT
#WC_MENU_GLOBAL_EFFECT_SNOW
#WC_CAN_NOT_LOAD_ASSET_OBJECT
#WC_CAN_ON_NOT_CREATE_ASSET_WINDOW
#WC_MENU_SHOW_SCROLL_TEXT
#WC_MENU_MAP_GUI_ON
#WC_MENU_MAP_GUI_OFF
#WC_MENU_UPDATE_ASSETS
#WC_MENU_OPEN_ASSET_DRAWER
#WC_MENU_OPEN_ASSET_SOUND_DRAWER
#WC_MENU_GO_TO_MAP_START
#WC_GLOBAL_EFFECT_SNOW
#WC_GLOBAL_EFFECT_NONE
EndEnumeration

Enumeration
#GAD_CONTAINER
#LAST_UI_GADGET
#NOTHING
    
EndEnumeration


; IDE Options = PureBasic 6.03 beta 4 LTS (Windows - x64)
; CursorPosition = 16
; FirstLine = 128
; EnableXP
; EnableUser
; CPU = 1
; DisableDebugger
; EnableCompileCount = 0
; EnableBuildCount = 0
; EnableExeConstant