; starcomm_display.pbi
; Display and help: RedrawGalaxy, PrintHelpGalaxy, PrintAbout, PrintHelpTactical
; XIncluded from starcomm.pb

Procedure RedrawGalaxy(*p.Ship)
  ClearConsole()
  ResetColor()
  PrintN("Starship Console: (Galaxy + Tactical)")
  ConsoleColor(#C_DARKGRAY, #C_BLACK)
  PrintN("Galaxy: (" + Str(gMapX) + "," + Str(gMapY) + ") of " + Str(#GALAXY_W) + "x" + Str(#GALAXY_H) + " Type HELP for commands")
  ResetColor()
  PrintN("")
  PrintStatusGalaxy(*p)
  PrintMap()
  PrintDivider()
  PrintN("Recent:")
  PrintLog()
  PrintDivider()
EndProcedure



Procedure PrintHelpGalaxy()
  PrintDivider()
  PrintN("Galaxy Commands:")
  PrintCmd("HELP")
  PrintN("    Show this help")
  PrintN("")
  PrintCmd("ABOUT")
  PrintN("    Show app info (name, version, creator, email, website)")
  PrintN("")
  PrintCmd("STATUS")
  PrintN("    Show ship status, fuel, ore, and systems")
  PrintN("")
  PrintCmd("ALLOC <engines> <weapons> <shields>")
  PrintN("    Set reactor power distribution (sum must be <= 100)")
  PrintN("    Default: 33 34 33")
  PrintN("    Example: ALLOC 40 40 20")
  PrintN("")
  PrintCmd("CREW")
  PrintN("    Show crew members and their experience")
  PrintN("")
  PrintCmd("LOG <search>")
  PrintN("    View captain's log or search for entries")
  PrintN("    LOG ARCHIVES - list all archives")
  PrintN("    LOG ARCHIVE <1-10> <search> - view archive")
  PrintN("    LOG PURGE YES - delete all current log entries")
  PrintN("    Example: LOG        (show recent)")
  PrintN("    Example: LOG planet (search for 'planet')")
  PrintN("")
  PrintCmd("MAP")
  PrintN("    Show the sector map")
  PrintN("    Legend:")
  PrintLegendLine("      ")
  PrintN("      X=Current map M=Mission map !=Mission target")
  PrintN("")
  PrintCmd("CLEAR")
  PrintN("    Clear console and refresh the galaxy map")
  PrintN("")
  PrintCmd("UNDO")
  PrintN("    Undo last command (restore position and resources)")
  PrintN("    Useful if you get sucked into a black hole or sun!")
  PrintN("")
  PrintCmd("UPGRADES")
  PrintN("    Show installed shipyard upgrades")
  PrintN("")
  PrintCmd("FLEET")
  PrintN("    Manage your fleet (up to 5 computer-controlled ships)")
  PrintN("    FLEET Rank is based on your lowest crew level.")
  PrintN("    - FLEET ADD        : Clone your current ship for free (at starbases).")
  PrintN("    - BUY HEADHUNTER   : Hire a specialized mercenary ship (500 cr).")
  PrintN("      (Roles: HELM, WEAPONS, SHIELDS, ENGINEERING)")
  PrintN("    - FLEET REMOVE     : Remove the last ship added to the fleet.")
  PrintN("    - FLEET            : Show current fleet status and hull health.")
  PrintN("")
  PrintCmd("SCAN")
  PrintN("    Show non-empty contents of adjacent sectors")
  PrintN("")
  PrintCmd("LONGSCAN")
  PrintN("    Long range scan - shows sectors within 2 steps")
  PrintN("")
  PrintCmd("NAV <heading> <steps>")
  PrintN("    Move using compass heading: 0=N, 45=NE, 90=E, 135=SE,")
  PrintN("    180=S, 225=SW, 270=W, 315=NW")
  PrintN("    Costs 1 fuel per sector")
  PrintN("    Examples: NAV 0 2 | NAV 90 3 | NAV 315 1")
  PrintN("")
  PrintCmd("WARP <x> <y>")
  PrintN("    Warp to a specific galaxy location (right side map)")
  PrintN("    Costs 5 dilithium, 10 turn cooldown between warps")
  PrintN("    Note: Pirate interdiction risk unless warping into HQ sector.")
  PrintN("    Example: WARP 3 2")

  PrintN("")
  PrintCmd("MINE")
  PrintN("    Mine ore when in a planet sector (O), costs 2 fuel")
  PrintN("    Can also mine dilithium crystals (D)")
  PrintN("    Example: MINE")
  PrintN("")
  PrintCmd("LAUNCHPROBE <x> <y>")
  PrintN("    Launch a probe to scan a distant galaxy sector")
  PrintN("    Reveals all stars, planets, enemies, bases, etc.")
  PrintN("    Example: LAUNCHPROBE 3 2")
  PrintN("")
  PrintCmd("LAUNCHSHUTTLE [LAUNCH|RECALL|MINE] [crew]")
  PrintN("    Launch shuttle craft (must be docked at starbase)")
  PrintN("    LAUNCHSHUTTLE LAUNCH [n] - Launch with 1-" + Str(gShuttleMaxCrew) + " crew")
  PrintN("    LAUNCHSHUTTLE RECALL    - Return shuttle, transfer cargo to ship")
  PrintN("    LAUNCHSHUTTLE MINE      - Collect resources from planet/cluster")
  PrintN("    Can attack enemies in combat or mine resources from planets")
  PrintN("    Shuttle capacity: " + Str(gShuttleMaxCargo) + " units ore/dilithium, up to " + Str(gShuttleMaxCrew) + " crew")
  PrintN("")
  PrintCmd("TRANSPORTER <ORE|DILITHIUM|ALL>")
  PrintN("    Beam up mined resources from planet/cluster to cargo")
  PrintN("    Use after MINE to transport extracted resources")
  PrintN("    Example: TRANSPORTER ALL")
  PrintN("")
  PrintCmd("REFUEL")
  PrintN("    Convert dilithium crystals to fuel (10 fuel per crystal)")
  PrintN("    Example: REFUEL")
  PrintN("")
  PrintCmd("DOCK")
  PrintN("    Dock when in a starbase (%), shipyard (+), or refinery (R)")
  PrintN("    Starbases/shipyards: repair/refuel/rearm")
  PrintN("    Refineries: REFINE ore / dilithium, SELL ore/metals")
  PrintN("    Starcomm HQ ($): INTEL, ORDERS, BANK, and RECALL beacon")
  PrintN("    Example: DOCK")
  PrintN("")
  PrintN("  HQ Commands (when docked at $):")
  PrintN("    BANK             - Deposit or withdraw credits for safekeeping")
  PrintN("    INTEL            - Galaxy-wide threat report and Planet Killer tracking")
  PrintN("    ORDERS           - Check HQ mission progress and tier rewards")
  PrintN("    RECALL           - Arm an emergency beacon to jump home from any sector")
  PrintN("")
  PrintN("  Refinery Commands (when docked at R):")
  PrintN("    REFINE           - Convert 1 ore to random refined metal (free)")
  PrintN("    REFINE ALL       - Convert all ore in cargo to refined metals")
  PrintN("    BUY <metal> <n>  - Buy refined metals for trading (e.g. BUY IRON 10)")
  PrintN("    SELL ORE         - Sell all ore (1 credit each)")
  PrintN("    SELL <metal>     - Sell specific refined metal (IRON, TIN, etc.)")
  PrintN("    SELL ALL         - Sell all cargo")
  PrintN("")
  PrintN("  Shipyard Commands (when docked at +):")
  PrintN("    [A-L]            - Select a standard Tier 1 upgrade (e.g. A for Hull)")
  PrintN("    [M-Q]            - Select an Advanced Tier 2 upgrade (Requires 21 T1 installs)")
  PrintN("")

  PrintCmd("RECRUIT <number>")
  PrintN("    Hire a recruit (available at starbases)")
  PrintN("    RECRUIT HEAD <role> - Hire a Level 3 expert (500 cr)")
  PrintN("    Example: RECRUIT 1 | RECRUIT HEAD HELM")
  PrintN("")
  PrintCmd("JETTISON <ORE|DILITHIUM>")
  PrintN("    Dump cargo into space to lighten ship or escape hunters")
  PrintN("    Jettisoned cargo appears as 'c' on the map and can be")
  PrintN("    recovered later using the TRANSPORTER command.")
  PrintN("    Example: JETTISON DILITHIUM")
  PrintN("")
  PrintCmd("DISMISS <role>")
  PrintN("    Dismiss crew member: HELM, WEAPONS, SHIELDS, or ENGINEERING")
  PrintN("    Example: DISMISS WEAPONS")
  PrintN("")
  PrintCmd("CLEAR")
  PrintN("    Clear console and refresh the galaxy map display")
  PrintN("    Example: CLEAR")
  PrintN("")
  
  If gCheatsUnlocked = 1
    PrintCmd("SHOWMETHEMONEY")
    PrintN("    Cheat: +500 credits (works in galaxy mode)")
    PrintN("")
    PrintCmd("POWEROVERWHELMING")
    PrintN("    Cheat: all stats x2 for 30 turns")
    PrintN("")
    PrintCmd("MINER2049ER")
    PrintN("    Cheat: fill cargo, fuel, probes")
    PrintN("")
    PrintCmd("SPAWNYARD")
    PrintN("    Cheat: spawn a shipyard in current sector")
    PrintN("")
    PrintCmd("SPAWNBASE")
    PrintN("    Cheat: spawn a starbase in current sector")
    PrintN("")
    PrintCmd("SPAWNHQ")
    PrintN("    Recovery: place Starcomm HQ at your position (only if none exists in galaxy)")
    PrintN("")
    PrintCmd("SPAWNREFINERY")
    PrintN("    Cheat: spawn a refinery in current sector")
    PrintN("")
    PrintCmd("SPAWNCLUSTER")
    PrintN("    Cheat: spawn a dilithium cluster in current sector")
    PrintN("")
    PrintCmd("SPAWNWORMHOLE")
    PrintN("    Cheat: spawn a wormhole in current sector")
    PrintN("")
    PrintCmd("SPAWNANOMALY")
    PrintN("    Cheat: spawn a spatial anomaly in current sector")
    PrintN("")
    PrintCmd("SPAWNPLANETKILLER")
    PrintN("    Cheat: spawn a Planet Killer in current sector")
    PrintN("")
    PrintCmd("REMOVESPAWN")
    PrintN("    Remove spawned objects (base, yard, cluster, wormhole, anomaly, planetkiller)")
    PrintN("")
  EndIf
  
  PrintCmd("SAVES")
  PrintN("    Open Save Game Manager (list, load, delete slots)")
  PrintN("")
  PrintCmd("SAVE <name>")
  PrintN("    Save current session to a named slot (default: autosave)")
  PrintN("    Example: SAVE mygame")
  PrintN("")
  PrintCmd("LOAD <name>")
  PrintN("    Load session from a named slot (default: autosave)")
  PrintN("    Example: LOAD mygame")
  PrintN("")
  PrintCmd("DELETE <name>")
  PrintN("    Delete a named save slot")
  PrintN("")
  PrintN("")
  PrintN("  Notes:")
  PrintN("    Deliver missions complete when you DOCK at the destination base.")
  PrintN("    Survey missions complete when you SCAN while at the destination planet.")
  PrintN("")
  PrintN("  Combat:")
  PrintN("    Enemies are marked E. Enemy sectors trigger contact and may lead to tactical combat.")
  PrintN("    Pirate (P) aggression scales with your DILITHIUM cargo:")
  PrintN("      0-9: Mostly ignore/avoid you | 10-19: Moderate interest | 20+: Aggressive")
  PrintN("    In tactical mode, type HELP for PHASER/TRACTOR/TRANSPORTER/TORPEDO/MOVE/ALLOC/FLEE.")

  PrintN("")
  PrintN("  Hazards:")
  PrintN("    # = Wormhole (teleports you to a random map/sector, costs 1 fuel)")
  PrintN("    ? = Black hole (gravity well; on entry: random teleport, severe damage + scramble, or destruction)")
  PrintN("    S = Sun (fatal; gravity well may pull you in if adjacent)")
  PrintN("    c = Cargo Container (recoverable resources)")
  PrintN("")
  PrintCmd("MACRO <sub> [name]")
  PrintN("    Mini-program system - record and replay any sequence of game commands.")
  PrintN("    Macros are saved as plain '.txt' files in the 'macros' folder.")
  PrintN("    MACRO LIST            - List all saved macros")
  PrintN("    MACRO CREATE <name>   - Create a new macro (enter commands line by line)")
  PrintN("    MACRO RUN    <name>   - Run a macro (commands execute automatically)")
  PrintN("    MACRO EDIT   <name>   - Edit / replace an existing macro")
  PrintN("    MACRO SHOW   <name>   - Display the commands inside a macro")
  PrintN("    MACRO DELETE <name>   - Delete a macro file")
  PrintN("    MACRO STOP            - Abort the currently running macro")
  PrintN("")
  PrintN("    Special macro lines (not sent to the game as commands):")
  PrintN("    ; <text>              - Comment line (skipped during playback)")
  PrintN("    PAUSE                 - Pause playback; press Enter to continue,")
  PrintN("                            type 'stop' to abort")
  PrintN("    DELAY <ms>            - Wait N milliseconds (0-5000) before next command")
  PrintN("    CHAIN <name>          - Splice another macro in at the current position")
  PrintN("    REPEAT <n>            - Repeat the following block n times (max 20)")
  PrintN("    END_REPEAT            - End of a REPEAT block")
  PrintN("")
  PrintN("    Conditional lines (run <command> only when condition is true):")
  PrintN("    IF_FUEL_LOW    <cmd>   - fuel below 25%")
  PrintN("    IF_HULL_LOW    <cmd>   - hull below 40%")
  PrintN("    IF_SHIELDS_LOW <cmd>   - shields below 30%")
  PrintN("    IF_TORP_EMPTY  <cmd>   - torpedoes = 0")
  PrintN("    IF_CARGO_FULL  <cmd>   - ore cargo at maximum capacity")
  PrintN("    IF_DILITHIUM_LOW <cmd> - dilithium below 5 crystals")
  PrintN("    IF_DOCKED      <cmd>   - ship is currently docked")
  PrintN("    IF_NOT_DOCKED  <cmd>   - ship is not docked")
  PrintN("")
  PrintN("    Example 'patrol' macro:")
  PrintN("      REPEAT 3")
  PrintN("      NAV 0 2")
  PrintN("      NAV 90 2")
  PrintN("      SCAN")
  PrintN("      IF_FUEL_LOW REFUEL")
  PrintN("      NAV 180 2")
  PrintN("      NAV 270 2")
  PrintN("      END_REPEAT")
  PrintN("")
  PrintCmd("TERMINAL")
  PrintN("    Open the Ship Computer Terminal (onboard interactive system)")
  PrintN("    Sub-commands inside the terminal:")
  PrintN("      STATUS   - System status (hull, shields, fuel, system states)")
  PrintN("      DIAG     - Full diagnostics with repair/resupply recommendations")
  PrintN("      DB ALL   - Entity database summary (enemies, planets, bases, hazards)")
  PrintN("      DB ENEMY | DB PLANET | DB BASE | DB HAZARD   - detailed entries")
  PrintN("      THREAT   - Scan current sector for hostile contacts")
  PrintN("      CARGO    - Detailed cargo manifest")
  PrintN("      HISTORY  - Last 10 captain's log entries")
  PrintN("      ALERTS   - Colour-coded alert status for all ship systems")
  PrintN("      EXIT     - Close terminal and return to galaxy mode")
  PrintN("")
  PrintCmd("QUIT")
  PrintCmd("EXIT")
  PrintN("    Exit the game")
  PrintDivider()
EndProcedure

Procedure PrintAbout()
  PrintDivider()
  ConsoleColor(#C_LIGHTGREEN, #C_BLACK)
  PrintN(#APP_NAME + " - " + version)
  ResetColor()
  PrintN("-----------------------")
  PrintN("Creator: David Scouten (zonemaster60)")
  PrintN("Email: " + #EMAIL_NAME)
  PrintN("Website: https://github.com/zonemaster60")
  PrintDivider()
EndProcedure

Procedure PrintHelpTactical()
  PrintDivider()
  PrintN("Tactical Commands:")
  PrintCmd("HELP")
  PrintN("    Show this help")
  PrintN("")
  PrintCmd("ABOUT")
  PrintN("    Show app info (name, version, creator, email, website)")
  PrintN("")
  PrintCmd("STATUS")
  PrintN("    Show tactical status (range, hull, shields, capacitor, torps)")
  PrintN("")
  PrintCmd("SCAN")
  PrintN("    Show detailed sensor report if within SensorRange")
  PrintN("")
  PrintCmd("ALLOC <engines> <weapons> <shields>")
  PrintN("    Set reactor power distribution (sum must be <= 100)")
  PrintN("    Default: 33 34 33")
  PrintN("    Examples: ALLOC 40 40 20 | ALLOC 33 34 33")
  PrintN("")
  PrintCmd("MOVE <APPROACH|RETREAT|HOLD> <amount>")
  PrintN("    Change range; amount is limited by Engines allocation")
  PrintN("    Aliases: CLOSER/IN = APPROACH, AWAY/OUT = RETREAT")
  PrintN("    Costs 1 fuel per MOVE")
  PrintN("    Examples: MOVE APPROACH 2 | MOVE AWAY 1 | MOVE HOLD")
  PrintN("")
  PrintCmd("PHASER <power>")
  PrintN("    Fire phasers using WeaponCap; power is capped per turn by PhaserBanks")
  PrintN("    Tip: if WeaponCap is 0, use END to recharge or ALLOC more to weapons")
  PrintN("    Example: PHASER 40")
  PrintN("")
  PrintCmd("TORPEDO <count>")
  PrintN("    Fire 1+ torpedoes; count capped by TorpedoTubes and remaining torps")
  PrintN("    Effective range: <= 24")
  PrintN("    Example: TORPEDO 1 | TORPEDO 2")
  PrintN("")
  PrintCmd("TRACTOR <HOLD|PULL|PUSH>")
  PrintN("    Tractor beam (green) - costs 1 fuel/dilithium per use")
  PrintN("    HOLD - lock enemy in place, prevents movement this turn")
  PrintN("    PULL - pull enemy 2 sectors closer (1 dilithium or fuel)")
  PrintN("    PUSH - push enemy into adjacent hazard (sun/blackhole/wormhole)")
    PrintN("  Example: TRACTOR HOLD | TRACTOR PULL | TRACTOR PUSH")
  PrintN("")
  PrintCmd("TRANSPORTER <ATTACK>")
  PrintN("    Beam away team to enemy ship for boarding action")
  PrintN("    ATTACK - send away team to attack and capture enemy")
  PrintN("    Success depends on power, crew size, and enemy range")
  PrintN("    Example: TRANSPORTER ATTACK")
  PrintN("")
  PrintCmd("SHUTTLE <ATTACK|INFO>")
  PrintN("    Launch shuttle for combat operations (must be launched in galaxy mode)")
  PrintN("    ATTACK - shuttle attacks enemy ship (range <= " + Str(gShuttleAttackRange) + ")")
  PrintN("    INFO   - show shuttle status")
  PrintN("    Shuttle has its own crew, can damage enemy systems")
  PrintN("    Example: SHUTTLE ATTACK")
  PrintN("")
  PrintCmd("FLEE")
  PrintN("    Attempt to disengage; success improves at longer range")
  PrintN("    Example: FLEE")
  PrintN("")
  PrintCmd("END")
  PrintN("    End your turn (regen/repair happens, then enemy acts)")
  PrintN("")
  PrintCmd("QUIT")
  PrintCmd("EXIT")
  PrintN("    Exit the game")
  PrintDivider()
EndProcedure
