[gui]
Title=Launcher
; icon=launcher.ico
FormWidth=170
FormHeight=60
Margin=0
Columns=1
Wow64=1
Esc=1
BtnAlign = 256
LargeIcon = 0
BtnMinH = 30



[1]
name=AkelPad
hint=Сторонний редактор кода
exe=C:\AkelPad\AkelPad.exe
exit = 1

[2]
name=Au3Info
hint=Информация об элементах окна при наведении мыши
exe=C:\AutoIt3\Au3Info.exe
exit = 1


