MENUE_TITLE
FILE
#E_MENU_LOAD_DEFAULT
Load Default AI File
#E_MENU_SAVE_DEFAULT
Save AI file As Default
#E_MENU_LOAD_FILE
Load AI File
#E_MENU_SAVE_AS
Save AI File As
#E_MENU_SAVE
Save AI
#E_MENU_ABOUT
About
#E_MENU_QUIT
Quit
MENUE_TITLE
GFX
#E_MENU_SET_GFX_OBJECT
Set GFX Object
#E_MENU_GFX_TO_FRONT
Show GFX
#E_MENU_SHOW_ASSET_FOLDER
Show Asset Folder
MENUE_TITLE
ACTIVATE NOT DEFINED
#E_MENU_ACTIVATE_NOT_ACTIVATED
Set Basic Data for Not Defined GFX (!TAKE CARE!)
MENUE_TITLE
DEVELOPER SECTION
#E_MENU_Ai42_REBUILD
REBUILD/RENEW ALL ai42 FILES?

