[gui]
Title=Launcher
; icon=launcher.ico
FormWidth=170
FormHeight=580
Margin=0
Columns=1
Wow64=1
Esc=1
BtnAlign = 256
LargeIcon = 0

[2]
name=Au3Info
hint=Информация об элементах окна при наведении мыши
exe=C:\AutoIt3\Au3Info.exe
exit = 1

[3]
name=LazyCoder
hint=Альтернативный автоподстановщик кода
exe=C:\Tools\LazyCoder\LazyCoder.exe
exit = 1

[4]
name=MessageRequester
exe=C:\Tools\MessageRequester.exe
exit = 1

[5]
name=PureFORM
hint=Редактор форм
exe=C:\Tools\PureFORM\PureFORM.exe
exit = 1

[6]
name=Translated
exe=C:\Tools\Translated\Translated.exe
hint=Переводчик элементов GUI программы
exit = 1

[7]
name=Dbgview
hint=Отладчик DLL
exe=C:\Tools\Dbgview.exe
exit = 1

[8]
name=Panel_Function
hint=Панель функций
exe=C:\Tools\Panel_Function\Panel_Function.exe
exit = 1

[9]
name=Advanced Search
hint=Поиск в интернете
exe=C:\Tools\Advanced_Search\Advanced_Search.exe
exit = 1

[10]
name=IceDesign
hint=Редактор форм
exe=C:\Tools\IceDesign\IceDesign_Demo.exe
exit = 1

[11]
name=RegExp
hint=Тест регулярных выражений
exe=C:\Tools\RegExpPB\RegExpPB.exe
exit = 1

[12]
name=Запуск
hint=Запуск с отладчиком для теста
exe=C:\Program Files\PureBasic\Compilers\pbcompiler.exe
arg=/XP /DPIAWARE -q
exit = 1

[13]
name=Компилировать
hint=Создаёт исполняемый файл (без иконки)
exe=C:\Program Files\PureBasic\Compilers\pbcompiler.exe
arg=/XP /DPIAWARE -q /EXE
exit = 1

[14]
name=Проверка кода
hint=Проверка кода
exe=C:\Program Files\PureBasic\Compilers\pbcompiler.exe
arg=/XP /DPIAWARE -k
exit = 1

[15]
name=Отладчик
hint=Отладчик
exe=C:\Program Files\PureBasic\Compilers\pbcompiler.exe
arg=/XP /DPIAWARE --debugger
exit = 1

[16]
name=Справка
hint=Справка CHM
exe=C:\Tools\Help\Help.exe
exit = 1

[17]
name=Получить ASM-код
hint=Получить ASM-код
exe=C:\Program Files\PureBasic\Compilers\pbcompiler.exe
arg=/XP /DPIAWARE -q /COMMENTED
exit = 1

[18]
name=Прерпоцессинг
hint=Прерпоцессинг
exe=C:\Program Files\PureBasic\Compilers\pbcompiler.exe
arg=/XP /DPIAWARE -q -pp
exit = 1

[19]
name=Компилировать DLL
hint=Компилировать DLL
exe=C:\Program Files\PureBasic\Compilers\pbcompiler.exe
arg=/XP /DPIAWARE -q /EXE /DLL
exit = 1

[20]
name=Получить Си-код
hint=Получить Си-код
exe=C:\Program Files\PureBasic\Compilers\pbcompilerc.exe
arg=/XP /DPIAWARE -q /COMMENTED
exit = 1
