
[none]
aaaaaa|2=.+
aaaaaa|2=.+
aaaaaa|2=.+
aaaaaa|2=.+
aaaaaa|2=.+
aaaaaa|2=.+
aaaaaa|2=.+
aaaaaa|2=.+
aaaaaa|2=.+
aaaaaa|2=.+
aaaaaa|2=.+
aaaaaa|2=.+
aaaaaa|2=.+
aaaaaa|2=.+
aaaaaa|2=.+
aaaaaa|2=.+
aaaaaa|2=.+
aaaaaa|2=.+
aaaaaa|2=.+
aaaaaa|2=.+
aaaaaa|2=.+
aaaaaa|2=.+

[txt]
FDCEAE|2=\d
CEDF99|1="[^"]+?"
BFCAA9|2=[a-zA-Z]
FF8080|3=[\[\](){}]+?

[ini,hhp,desktop]
009FFF|2=^[	 ]*?\[[^\[\]]+\][	 ]*?$
F3CF70|1="[^"]+?"
6588F7|2==[A-Fa-f\d]+?
C0AD72|2==[^\r\n]+?
FF8080|2=[=]
71AE71|2=^[	 ]*?[;#].*?$

[reg]
72ADC0|2==Hex\(\d+\):
72ADC0|2==dword:
72ADC0|2==Hex:
009FFF|2=^[	 ]*?\[[^\[\]]+\][	 ]*?$
F666FF|1=^\[.+?\\
FF8080|2=^[	 ]*?\[-[^\[\]]+\][	 ]*?$
AAAAAA|1="[^"]+?"
EDD6ED|1=^.+?=
FF8080|2=[=]
AFE7B3|1="\\"[bcdefx]:\\\\.+
AFE7B3|1="[bcdefx]:\\\\.+
FDCEAE|2=^@
EBCB9C|2=:[\dabcdef,]+\\$
EBCB9C|2=^[	 ]*?[\dabcdef,]+\\?$
D997DE|2={[\dabcdef-]+?}
71AE71|2=^[	 ]*?;.*?

[pb,pbi,pbf]
D29A6C|2=\w+\.[sfdqbliwcapu]\>
FFFF80|2=\.[sfdqbliwcapu]\>
009FFF|2=^[	 ]*?\w+$
009FFF|2=^[	 ]*?\w+[ ]+?
D29A6C|2=\w+[	 ]+?=
D29A6C|2=[,(][ ]?\w+
EBCB9C|2=\<\d+\>
AAA6DB|2=\w+\(
7D8AE6|2=\w+_\(
D29A6C|2=\w+\$
D998DE|2=#\w+\$?
FF8080|2=[\=\+\*\/\-(),><]+
F3CF70|2=[*@]\w+
BFCAA9|1="[^"]+?"
FFFF80|2=\w+:
00A8BF|2=\w+::
FFA704|2=\\\w+
72ADC0|2=\$[a-f\d]+\>
71AE71|2=;.+

[au3]
009FFF|2=\<[a-z]+\>
72ADC0|2=[=/.][ ]?[\w.\|%]+
EBCB9C|2=\<\d+\>
AAA6DB|2=\<\w+\(
7D8AE6|2=\<_\w+\(
D29A6C|2=\$\w+
FF8080|2=[\=\+\*\/\-(),><&\[\]]+
AAAAAA|2=#\w+[ ]*?[= ].+?$
F666FF|2=[@#]\w+
AAAAAA|1=["'][^"]*?["']
BFCAA9|2=\\[\w.]+
FFA704|2={\w+}
EBCB9C|2=\<0x[a-f\d]+\>
71AE71|2=;.+

[css]
AAA6DB|2=\<[pab]\>
AAA6DB|2=^[\w,	 {-]+$
AAA6DB|2=\<\w+[.\[]
D29A6C|2=\<[\w-]+:
AAA6DB|2=\<\w:
00C2BB|2=:[	 ]*?[a-zA-Z-]+
AAA6DB|2=\<\w+\(
00C2BB|2=\<\w+;
B7C46A|2=\[[\w*~$|^]+=
8FAF9F|2==[\w"]+\]
FF8080|2=[,\[\](){};:!.=>]+
009FFF|2=\.[\w-]+
D998DE|2=!\w+\>
F666FF|2=#[\w-]+\>
EBCB9C|2=\<\d+[pe%]?[xm]?
EBCB9C|2=\<\d+\>
EBCB9C|2=\<\d+\.\d+[e%]?m?
72ADC0|2=#[a-f\d]+\>
dd8080|2=/[\w./-]+\>
71AE71|2=/\*[^/]*?
71AE71|2=[^/]*?\*/
71AE71|2=/\*.*?\*/

[cmd,bat]
D29A6C|2=%%\w+
D29A6C|2=%\w+%
D29A6C|2=!\w+!
009FFF|2=\<if\>
009FFF|2=\<else\>
009FFF|2=\<set\>
009FFF|2=\<for\>
009FFF|2=\<echo\>
009FFF|2=\<setlocal\>
009FFF|2=\<do\>
009FFF|2=\<in\>
FF8080|2=[\=\+\*\/\-(),><@]+
71AE71|2=^[ 	]*?::.+
71AE71|2=^[ 	]*?rem.+

[htm,html]
009FFF|2=<[^<>]+>
C0AD72|2=[a-z]+="[^\r\n<>]+?"
FF8080|2=href=
71AE71|2=<!--.*?-->

[xml,fb2,hhk,hhc]
009FFF|2=<[^<>]+>
8296AE|2=[a-z]+="[^\r\n<>]+?"
DCA3A3|2=[a-z]+=
71AE71|2=^[	 ]*?[^	 <].+?$
71AE71|2=<!--.*?$
71AE71|2=^.*?-->

[js]
AAA6DB|2=\w+\(
C0AD72|2=\[.+?\]
FF8080|2=[\=\+\*\/\-(),><{}\[\]&\|;]+
D29A6C|2=\$\([\w']+\)
EBCB9C|2=\<\d+\>
71AE71|2=///.*?
71AE71|2=/\*.*?
71AE71|2=\*/
;71AE71|2=/\*.+?\*/
009FFF|2=\<var\>
009FFF|2=\<function\>
009FFF|2=\<if\>
009FFF|2=\<for\>

; grub.cfg
[cfg]
; 009FFF|2=\<menuentry\>
FF66FF|2=UUID=[\w-]+?
FF9CB8|2=[\w-]+?=
FF8080|2=[\=\+\*\/\-(),><{}\[\]&\|;]+
EBCB9C|2=\<loop\>
EBCB9C|2=\<UUID\>
009FFF|2=\<then\>
7EBBBD|2=/[.\w/-]+?
7EBBBD|2=="/.+?"
FF8080|2=menuentry ["'].+?["']
FF8080|2=submenu ["'].+?["']
D997DE|2=insmod \w+?
009FFF|2=\<insmod\>
009FFF|2=^[	 ]*?\w+$
009FFF|2=^[	 ]*?\w+[	 ]+?
C0AD72|2=--[\w-]+
; 80C949|2=\<echo[	 ]+?["'].+?["']
80C949|2=^[	 ]*?echo.+?$
D29A6C|2=\$\{.+?\}
D29A6C|2=\$\w+
71AE71|2=#.+

[lst]
009FFF|2=^[	 ]*?\w+\>
009FFF|2=||[	 ]*?\w+\>
CEDF99|2=\w+=[.;\w/%-]+
FF99cc|2=\w+=
FF8080|2=[=+*/(),><{}\[\]&\|;]+
7EBBBD|2=/[.\w/%-]+?
EBCB9C|2=\<0x[a-f\d]+\>
C0AD72|2=--[\w-]+
EBCB9C|2=\<[hfcr]d\d+\>
F666FF|2=[a-f\d]+-[a-f\d-]+$
D7D700|2=^[	 ]*?title.+?$
D29A6C|2=%\w+%
71AE71|2=#.+

[wcs]
F666FF|2=\<\d+\>
F666FF|2=\<0x[a-f\d]+\>
009FFF|2=^[	 ]*?[A-Z]+\>
009FFF|2=^[	 ]*?_[A-Z]+\>
D29A6C|2=\<[A-Z]+\d[	 ]*?,
D7D700|2=\<[A-Z]+\d\.[A-Z]+
D29A6C|2=%\w+%
D29A6C|2=[%&#$@]+\w+
FF8080|2=[=+*/(),><{}\[\]&\|;]+
D997DE|2=L-?\d+T-?\d+W-?\d+H-?\d+
DEDEBE|2=[а-яА-ЯЁё]+
71AE71|2=//.+

[rex]
71AE71=\{[\d,]+\}
D997DE=\.[*+]\??
C4C072=\\[fhrntvdswFHRNVDSW][*+]?\??
F666FF=\\[ABbZzQE]
F666FF=[$^|]
D997DE=\\x[0-9a-f]+
D997DE=\\x\{[0-9a-f][0-9a-f]\}
D997DE=\\\d\d\d\>
0080FF=[\[\]]\+?\??
FF8080=\(\?<?[:=!]
FF8080=\(\?[smixJU\-]+?:
FF8080=[()][+?]?

[bbcode]
D29A6C|2=\[/?[a-z]+\]
C0AD72|2=\[[a-z]+=[^\[\]]+\]
D29A6C|2=\[[a-z]+=
43AED9|2=\[url=[^\[\]]+
FF8080|2=\[url=
FF8080|2=\[/url\]
8CD0D3|2=\[/?b\]

[md]
00C2BB|2=^[	 ]*?:::.+?:::
AFE7B3|2=^[	 ]*?>+.+
777777|2=~~.+?~~
EBCB9C|2=#+[^#]+#+
EBCB9C|2=^[	 ]*?#+[^#]+
CEDF99|2=\*+[^\*]+\*+
CEDF99|2=^[	 ]*?\*+[^\*]+
DEDEBE|2=- .+
FF8080|2=- \[[ x*]\]
FCAF3E|2=^[	 ]*?\d+\. 
FF8080|2=^[	 ]*?[ |-]+[	 ]*?$
FF8080|2=\[.+?\]\(http.+?\)
43AED9|2=http[^	 \)]+?
C0AD72|2=`[^`]+`
FF8080|2=```+
EBD6EB|2=^[	 ]*?|.+?|[	 ]*?$
71AE71|2=<!---.+--->
